export const CssCursorStyles = {
    Alias: "alias",
    AllScroll: "all-scroll",
    Auto: "auto",
    Cell: "cell",
    ContextMenu: "context-menu",
    ColResize: "col-resize",
    Copy: "copy",
    Crosshair: "crosshair",
    Default: "default",
    EResize: "e-resize",
    EwResize: "ew-resize",
    Grab: "grab",
    Grabbing: "grabbing",
    Help: "help",
    Move: "move",
    NResize: "n-resize",
    NeResize: "ne-resize",
    NeswResize: "nesw-resize",
    NoDrop: "no-drop",
    None: "none",
    NotAllowed: "not-allowed",
    NwResize: "nw-resize",
    NwseResize: "nwse-resize",
    Pointer: "pointer",
    Progress: "progress",
    RowResize: "row-resize",
    SResize: "s-resize",
    SeResize: "se-resize",
    SwResize: "sw-resize",
    Text: "text",
    VerticalText: "vertical-text",
    WResize: "w-resize",
    Wait: "wait",
    ZoomIn: "zoom-in",
    ZoomOut: "zoom-out",
} as const;

export type CssCursorStyles = FromEnum<typeof CssCursorStyles>;
export type FromEnum<T> = T extends Record<string, string> ? T[keyof T] : never;
